### ISSUE TITLE
탭으로 자동완성 비활성화

### ISSUE THREAD

**Issue by ys27** [gomjellie/zsh-hangul#14]
탭으로 자동완성 (디렉토리 등등)이 갑자기 안돼서 테스트 해봤더니 이 플러그인이 활성화 되어있으면 탭이 안됩니다. 

체크해보니 zsh-hangul.zsh 의 Line 30: `zle -C _complete_dudgks menu-complete _complete_dudgks` 이 없으면 탭 기능은 돌아오는데 저걸 없애면 생기는 문제가 뭔지 아시는분이 체크해주시면 감사하겠습니다. 그리고 왜 한 커맨드에 `_complete_dudgks`이 두번 쓰이는지도 조금 궁금합니다. 

저는 일단 저 라인을 없앤 상태로 쓰고 테스트 해보겠습니다.

**Comment by gomjellie** [comment]
30번 라인을 없애면 ctrl + n 으로 영어를 한글로 바뀌는 기능을 못쓰네요.
해당 기능을 사용하지 않으면 30번 라인은 없어도 될것같습니다.

감사합니다!

**Comment by ys27** [comment]
감사합니다 저 기능은 안 쓰는 중이라 저는 괜찮은데 고칠 계획이시면 이슈를 열어놓을까요?

**Comment by gomjellie** [comment]
30번 라인 지워서 해결했습니다. 감사합니다!
